---
language: java
jdk: openjdk8

# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: required

# http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
  - $HOME/.m2

services:
  - docker

addons:
  apt_packages:
    - git

install:
    - echo "ivy.retrieve.log=default" >> etc/local.properties
    - echo "artifactory.host=artifacts.glencoesoftware.com" >> etc/local.properties
    - echo "artifactory.baseurl=https://${artifactory.host}/artifactory" >> etc/local.properties
    - echo "artifactory.repo=repo" >> etc/local.properties
    - git clone git://github.com/ome/omero-test-infra .omero


script:
    - .omero/docker srv

notifications:
  slack:
    secure: YoCiRg7KuG+jQdW2wD5aBVurfJoKTT+/bKexZD/t5w+WjR4oKi0eoj+La4niUHxmUGHmJAuRYq/7wpP7nq1RBOcXQYpq9S842tmhhQZeC2EGFGw3YlBBEQj9oqMl9JlcI4lTkSo4V/uCnwdrFAGfGaAjICuCnEb9rvBhsXeqYtU=
    on_success: change
