name: "Source Build"
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build OMERO from source
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install and run flake8
        run: |
          pip install flake8
          flake8 .
      - name: Build
        run: ./build.py
      - name: Rebuild
        run: ./build.py clean && ./build.py
