name: "Update version"
on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    name: Update dependencies
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: update version
        run: |
          dirs=("org/openmicroscopy/omero-blitz" "org/openmicroscopy/omero-common-test" "org/openmicroscopy/omero-gateway" "ome/OMEZarrReader")
          for dir in "${dirs[@]}"
          do
            : 
            values=(${dir//// })
            value=${values[${#values[@]}-1]}
            # get the latest version of the package
            repopath="https://artifacts.openmicroscopy.org/artifactory/ome.releases/${dir}"
            version=`curl -s ${repopath}/maven-metadata.xml | grep latest | sed "s/.*<latest>\([^<]*\)<\/latest>.*/\1/"`
            sed -i "s/versions.${value}=.*/versions.${value}=${version}/" etc/omero.properties
          done
      - name: update version Python
        run: |
          package="omero-scripts"
          version=`curl -Ls https://pypi.org/pypi/$package/json | jq -r .info.version`
          sed -i "s/versions.${package}=.*/versions.${package}=${version}/" etc/omero.properties
      - name: Set up configuration
        run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          labels: include
          token: ${{secrets.ACTION_API_TOKEN}}
          commit-message: "update dependencies"
          delete-branch: true
          title: "update dependencies"
          body: |
              - This PR contains changes from upstream repositories
  
              Auto-generated by [create-pull-request][1]
  
              [1]: https://github.com/peter-evans/create-pull-request

